// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: test.proto

#include "test.pb.h"
#include "test.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace test {

static const char* Hello_method_names[] = {
  "/test.Hello/HelloLys",
};

std::unique_ptr< Hello::Stub> Hello::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Hello::Stub> stub(new Hello::Stub(channel));
  return stub;
}

Hello::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_HelloLys_(Hello_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Hello::Stub::HelloLys(::grpc::ClientContext* context, const ::test::HelloReq& request, ::test::HelloRes* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_HelloLys_, context, request, response);
}

void Hello::Stub::experimental_async::HelloLys(::grpc::ClientContext* context, const ::test::HelloReq* request, ::test::HelloRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_HelloLys_, context, request, response, std::move(f));
}

void Hello::Stub::experimental_async::HelloLys(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::test::HelloRes* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_HelloLys_, context, request, response, std::move(f));
}

void Hello::Stub::experimental_async::HelloLys(::grpc::ClientContext* context, const ::test::HelloReq* request, ::test::HelloRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_HelloLys_, context, request, response, reactor);
}

void Hello::Stub::experimental_async::HelloLys(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::test::HelloRes* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_HelloLys_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::test::HelloRes>* Hello::Stub::AsyncHelloLysRaw(::grpc::ClientContext* context, const ::test::HelloReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::test::HelloRes>::Create(channel_.get(), cq, rpcmethod_HelloLys_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::test::HelloRes>* Hello::Stub::PrepareAsyncHelloLysRaw(::grpc::ClientContext* context, const ::test::HelloReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::test::HelloRes>::Create(channel_.get(), cq, rpcmethod_HelloLys_, context, request, false);
}

Hello::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Hello_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Hello::Service, ::test::HelloReq, ::test::HelloRes>(
          [](Hello::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::test::HelloReq* req,
             ::test::HelloRes* resp) {
               return service->HelloLys(ctx, req, resp);
             }, this)));
}

Hello::Service::~Service() {
}

::grpc::Status Hello::Service::HelloLys(::grpc::ServerContext* context, const ::test::HelloReq* request, ::test::HelloRes* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace test

